# Generated by Django 5.0.7 on 2024-07-18 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='institution',
            name='supported',
        ),
    ]
