# Generated by Django 5.0.7 on 2024-07-21 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donation', '0002_remove_institution_supported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
